name: Release

on:
    push:
        branches: ['main']
    workflow_dispatch:

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-20.04
        steps:
            - name: Wait on checks
              uses: lewagon/wait-on-check-action@master
              with:
                  ref: ${{ github.sha }}
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  check-name: 'Backend checks'

            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git config --global user.email github-actions@github.com
                  git config --global user.name github-actions

            - uses: dtolnay/rust-toolchain@stable

            - uses: baptiste0928/cargo-install@v2
              with:
                  crate: cargo-edit

            - uses: volta-cli/action@v4

            - name: Bump
              id: release
              uses: cocogitto/cocogitto-action@main
              with:
                  check-latest-tag-only: true
                  release: true
                  git-user: 'github-actions'
                  git-user-email: 'github-actions@github.com'

            - name: Generate Changelog
              run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

            - name: Upload github release
              uses: softprops/action-gh-release@v1
              with:
                  body_path: GITHUB_CHANGELOG.md
                  tag_name: ${{ steps.release.outputs.version }}
