name: Tauri

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
    types: [opened, synchronize]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  check:
    name: Check
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up environment with Volta
        uses: volta-cli/action@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Ubuntu dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev \
              build-essential \
              curl \
              wget \
              file \
              libssl-dev \
              libgtk-3-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev

      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2.2.0
        with:
          shared-key: whooosh
          workspaces: src-tauri

      - name: Getting dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn tauri build
