name: Tauri

on:
    pull_request:
        branches: ['**']
        types: [opened, synchronize]
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always
    SQLX_OFFLINE: true

jobs:
    check:
        name: Build
        permissions:
            contents: write
        strategy:
            fail-fast: true
            matrix:
                platform: [macos-latest, ubuntu-20.04, windows-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4

            - uses: Swatinem/rust-cache@v2
              with:
                  shared-key: whooosh-${{ matrix.platform }}
                  workspaces: src-tauri

            - uses: volta-cli/action@v4

            - uses: dtolnay/rust-toolchain@stable

            - if: matrix.platform == 'ubuntu-20.04'
              uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                  packages: libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev
                  version: 1.0

            - run: yarn install --immutable

            - run: yarn tauri build
